### PR TITLE
Add full5x5_r9 variable for electrons

### PR DESCRIPTION
**Pull request by zucchett**
Added a new variable (R9) for electrons. This one is needed to run the EGMSmearer class for the electron scale and resolution corrections after ntuplization. These corrections are also needed before applying the slew rate corrections for ReReco data.

Further info: https://twiki.cern.ch/twiki/bin/view/CMS/EGMSmearer

### CODE REVIEW

**Comment by gitytakahas** [comment]
it is ok to merge. But is this beyond Moriond ? 
I already produced up to V3 with current codes ... so I just wanted to make sure ...

**Comment by zucchett** [comment]
No, this is before Moriond. The recipe is quite new, though. It is ok for the MC V3, because all MC do not have this variable. For processing data it should be better to include it (at least for the processing with final JEC)

**Comment by gitytakahas** [comment]
hmmm, but i already started V3 production unfortunately ... 
For data, we can include it though

**Comment by zucchett** [comment]
Nevermind for this round, no problem! I know it was late, it will be for the next one

**Pull request merged**
