### PR TITLE
adding new electron IDs

### PR DESCRIPTION
**Pull request by gitytakahas**
- adding new electron IDs
- removing MVA MET from ntuple production options.

### CODE REVIEW

**Comment by gitytakahas** [comment]
@cgalloni 

I updated electron ID without isolation requirements (I also changed function name to "eleIDpassedWithoutIPandIsolation" but it should be ok for you). 

Note that, I also removed impact parameter requirements, as these are different depending on the analysis (HTT analysis uses different dz, dxy requirements). 

For HEEP electron ID, please check if I am doing correct thing (at least, I checked https://twiki.cern.ch/twiki/bin/view/CMS/HEEPElectronIdentificationRun2 and should be OK).

**Comment by cgalloni** [comment]
Yuta, would it be possible to leave the IP and Dz, Dxy requirement for the boostedID and then add also the other eleIDpassedWithoutIPandIsolation without those requirements? 
The fact is that I'd like to use the SF fromthe POG so the ID I use cannot be too different form the recommended oness. is it ok wuth you?

**Comment by gitytakahas** [comment]
yes ... let me modify then

**Comment by gitytakahas** [comment]
Looking at https://twiki.cern.ch/twiki/bin/viewauth/CMS/CutBasedElectronIdentificationRun2#Working_points_for_2016_data_for

it seems that d0 and dz is not part of ID now. How do you want to do this ?

**Comment by gitytakahas** [comment]
@cgalloni 
should be ok now.

**Pull request merged**
