### PR TITLE
Added samples for w-tagging in 76X

### PR DESCRIPTION
**Pull request by thaarres**

### CODE REVIEW

**Comment by ahinzmann** [comment]
I already added those here: #99

**Comment by clelange** [comment]
if the text files had names like top/QCD/WJets_*campaignname* etc. it'd be clear what's what

**Comment by ahinzmann** [comment]
Actually I already did the Phedex request for those samples

**Comment by thaarres** [comment]
Ok, I dint see the samples in the main repository https://github.com/UZHCMS/EXOVVNtuplizerRunII/tree/master/Ntuplizer/samples

**Comment by ahinzmann** [comment]
then you volunteered yourself to review my PR :-)

**Pull request closed without merging**
